<?php
/**
 * mailignwork GmbH
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com and you will be sent a copy immediately.
 *
 * @category   mailingwork
 * @package    Mailingwork_Sync
 * @copyright  Copyright (c) 2016 mailingwork GmbH (http://mailingwork.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img src="https://mailingwork.de/fileadmin/prototyp/img/mailingwork_logo.svg"/><br><br>
        <div style="padding-left: 30px;">
            <p> <strong style="color:#EA7601;">mailingwork v<?php echo $this->getVersion() ?> by</strong> <a target="_blank" href="http://mailingwork.de"><strong>mailingwork</strong></a></p>
        </div>
    </h4>
</div>